""" All CM model objects """

# pylint: disable=invalid-name,too-many-lines

from typing import Dict, List

from sklearn.ensemble import RandomForestClassifier  # type: ignore

from views.apps.model import api
from views.specs.models import cm
from views.specs.periods import get_periods

rf = RandomForestClassifier(n_jobs=-1, n_estimators=10_000)

# The currently latest model development run id
run_id = "d_2020_04_01"
periods: List[api.Period] = get_periods(run_id=run_id)
steps = [1, 3, 6, 9, 12, 18, 24, 30, 36, 38]

fullsample = api.Downsampling(share_positive=1.0, share_negative=1.0)

cm_sb_vdem_global = api.Model(
    name="cm_sb_vdem_global",
    col_outcome=cm["sb_vdem_global"]["col_outcome"],
    cols_features=cm["sb_vdem_global"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_global"],
)
cm_sb_wdi_global = api.Model(
    name="cm_sb_wdi_global",
    col_outcome=cm["sb_wdi_global"]["col_outcome"],
    cols_features=cm["sb_wdi_global"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_global"],
)
cm_sb_reign_global = api.Model(
    name="cm_sb_reign_global",
    col_outcome=cm["sb_reign_global"]["col_outcome"],
    cols_features=cm["sb_reign_global"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_global"],
)
cm_sb_all_global = api.Model(
    name="cm_sb_all_global",
    col_outcome=cm["sb_all_global"]["col_outcome"],
    cols_features=cm["sb_all_global"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_global"],
)
cm_ns_vdem_global = api.Model(
    name="cm_ns_vdem_global",
    col_outcome=cm["ns_vdem_global"]["col_outcome"],
    cols_features=cm["ns_vdem_global"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_global"],
)
cm_ns_wdi_global = api.Model(
    name="cm_ns_wdi_global",
    col_outcome=cm["ns_wdi_global"]["col_outcome"],
    cols_features=cm["ns_wdi_global"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_global"],
)
cm_ns_reign_global = api.Model(
    name="cm_ns_reign_global",
    col_outcome=cm["ns_reign_global"]["col_outcome"],
    cols_features=cm["ns_reign_global"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_global"],
)
cm_ns_all_global = api.Model(
    name="cm_ns_all_global",
    col_outcome=cm["ns_all_global"]["col_outcome"],
    cols_features=cm["ns_all_global"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_global"],
)
cm_os_vdem_global = api.Model(
    name="cm_os_vdem_global",
    col_outcome=cm["os_vdem_global"]["col_outcome"],
    cols_features=cm["os_vdem_global"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_global"],
)
cm_os_wdi_global = api.Model(
    name="cm_os_wdi_global",
    col_outcome=cm["os_wdi_global"]["col_outcome"],
    cols_features=cm["os_wdi_global"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_global"],
)
cm_os_reign_global = api.Model(
    name="cm_os_reign_global",
    col_outcome=cm["os_reign_global"]["col_outcome"],
    cols_features=cm["os_reign_global"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_global"],
)
cm_os_all_global = api.Model(
    name="cm_os_all_global",
    col_outcome=cm["os_all_global"]["col_outcome"],
    cols_features=cm["os_all_global"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_global"],
)

cm_sb_all_dummy = api.Model(
    name="cm_sb_all_dummy",
    col_outcome=cm["sb_all_dummy"]["col_outcome"],
    cols_features=cm["sb_all_dummy"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_all_25 = api.Model(
    name="cm_sb_all_25",
    col_outcome=cm["sb_all_25"]["col_outcome"],
    cols_features=cm["sb_all_25"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_acled_violence = api.Model(
    name="cm_sb_acled_violence",
    col_outcome=cm["sb_acled_violence"]["col_outcome"],
    cols_features=cm["sb_acled_violence"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_acled_protest = api.Model(
    name="cm_sb_acled_protest",
    col_outcome=cm["sb_acled_protest"]["col_outcome"],
    cols_features=cm["sb_acled_protest"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_cfshort = api.Model(
    name="cm_sb_cfshort",
    col_outcome=cm["sb_cfshort"]["col_outcome"],
    cols_features=cm["sb_cfshort"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_cflong = api.Model(
    name="cm_sb_cflong",
    col_outcome=cm["sb_cflong"]["col_outcome"],
    cols_features=cm["sb_cflong"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_demog = api.Model(
    name="cm_sb_demog",
    col_outcome=cm["sb_demog"]["col_outcome"],
    cols_features=cm["sb_demog"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_demog_conf = api.Model(
    name="cm_sb_demog_conf",
    col_outcome=cm["sb_demog_conf"]["col_outcome"],
    cols_features=cm["sb_demog_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_econ = api.Model(
    name="cm_sb_econ",
    col_outcome=cm["sb_econ"]["col_outcome"],
    cols_features=cm["sb_econ"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_econ_conf = api.Model(
    name="cm_sb_econ_conf",
    col_outcome=cm["sb_econ_conf"]["col_outcome"],
    cols_features=cm["sb_econ_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_inst = api.Model(
    name="cm_sb_inst",
    col_outcome=cm["sb_inst"]["col_outcome"],
    cols_features=cm["sb_inst"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_inst_conf = api.Model(
    name="cm_sb_inst_conf",
    col_outcome=cm["sb_inst_conf"]["col_outcome"],
    cols_features=cm["sb_inst_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_icgcw = api.Model(
    name="cm_sb_icgcw",
    col_outcome=cm["sb_icgcw"]["col_outcome"],
    cols_features=cm["sb_icgcw"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_icgcw_conf = api.Model(
    name="cm_sb_icgcw_conf",
    col_outcome=cm["sb_icgcw_conf"]["col_outcome"],
    cols_features=cm["sb_icgcw_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_neibhist = api.Model(
    name="cm_sb_neibhist",
    col_outcome=cm["sb_neibhist"]["col_outcome"],
    cols_features=cm["sb_neibhist"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_reign = api.Model(
    name="cm_sb_reign",
    col_outcome=cm["sb_reign"]["col_outcome"],
    cols_features=cm["sb_reign"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_reign_conf = api.Model(
    name="cm_sb_reign_conf",
    col_outcome=cm["sb_reign_conf"]["col_outcome"],
    cols_features=cm["sb_reign_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_reign_drought = api.Model(
    name="cm_sb_reign_drought",
    col_outcome=cm["sb_reign_drought"]["col_outcome"],
    cols_features=cm["sb_reign_drought"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_reign_drought_conf = api.Model(
    name="cm_sb_reign_drought_conf",
    col_outcome=cm["sb_reign_drought_conf"]["col_outcome"],
    cols_features=cm["sb_reign_drought_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_reign_coups = api.Model(
    name="cm_sb_reign_coups",
    col_outcome=cm["sb_reign_coups"]["col_outcome"],
    cols_features=cm["sb_reign_coups"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_reign_coups_conf = api.Model(
    name="cm_sb_reign_coups_conf",
    col_outcome=cm["sb_reign_coups_conf"]["col_outcome"],
    cols_features=cm["sb_reign_coups_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_vdem = api.Model(
    name="cm_sb_vdem",
    col_outcome=cm["sb_vdem"]["col_outcome"],
    cols_features=cm["sb_vdem"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_vdem_conf = api.Model(
    name="cm_sb_vdem_conf",
    col_outcome=cm["sb_vdem_conf"]["col_outcome"],
    cols_features=cm["sb_vdem_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_vdem_high = api.Model(
    name="cm_sb_vdem_high",
    col_outcome=cm["sb_vdem_high"]["col_outcome"],
    cols_features=cm["sb_vdem_high"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_all_dummy = api.Model(
    name="cm_ns_all_dummy",
    col_outcome=cm["ns_all_dummy"]["col_outcome"],
    cols_features=cm["ns_all_dummy"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_all_25 = api.Model(
    name="cm_ns_all_25",
    col_outcome=cm["ns_all_25"]["col_outcome"],
    cols_features=cm["ns_all_25"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_acled_violence = api.Model(
    name="cm_ns_acled_violence",
    col_outcome=cm["ns_acled_violence"]["col_outcome"],
    cols_features=cm["ns_acled_violence"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_acled_protest = api.Model(
    name="cm_ns_acled_protest",
    col_outcome=cm["ns_acled_protest"]["col_outcome"],
    cols_features=cm["ns_acled_protest"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_cfshort = api.Model(
    name="cm_ns_cfshort",
    col_outcome=cm["ns_cfshort"]["col_outcome"],
    cols_features=cm["ns_cfshort"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_cflong = api.Model(
    name="cm_ns_cflong",
    col_outcome=cm["ns_cflong"]["col_outcome"],
    cols_features=cm["ns_cflong"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_demog = api.Model(
    name="cm_ns_demog",
    col_outcome=cm["ns_demog"]["col_outcome"],
    cols_features=cm["ns_demog"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_demog_conf = api.Model(
    name="cm_ns_demog_conf",
    col_outcome=cm["ns_demog_conf"]["col_outcome"],
    cols_features=cm["ns_demog_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_econ = api.Model(
    name="cm_ns_econ",
    col_outcome=cm["ns_econ"]["col_outcome"],
    cols_features=cm["ns_econ"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_econ_conf = api.Model(
    name="cm_ns_econ_conf",
    col_outcome=cm["ns_econ_conf"]["col_outcome"],
    cols_features=cm["ns_econ_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_inst = api.Model(
    name="cm_ns_inst",
    col_outcome=cm["ns_inst"]["col_outcome"],
    cols_features=cm["ns_inst"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_inst_conf = api.Model(
    name="cm_ns_inst_conf",
    col_outcome=cm["ns_inst_conf"]["col_outcome"],
    cols_features=cm["ns_inst_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_icgcw = api.Model(
    name="cm_ns_icgcw",
    col_outcome=cm["ns_icgcw"]["col_outcome"],
    cols_features=cm["ns_icgcw"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_neibhist = api.Model(
    name="cm_ns_neibhist",
    col_outcome=cm["ns_neibhist"]["col_outcome"],
    cols_features=cm["ns_neibhist"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_reign = api.Model(
    name="cm_ns_reign",
    col_outcome=cm["ns_reign"]["col_outcome"],
    cols_features=cm["ns_reign"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_reign_conf = api.Model(
    name="cm_ns_reign_conf",
    col_outcome=cm["ns_reign_conf"]["col_outcome"],
    cols_features=cm["ns_reign_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_reign_drought = api.Model(
    name="cm_ns_reign_drought",
    col_outcome=cm["ns_reign_drought"]["col_outcome"],
    cols_features=cm["ns_reign_drought"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_reign_drought_conf = api.Model(
    name="cm_ns_reign_drought_conf",
    col_outcome=cm["ns_reign_drought_conf"]["col_outcome"],
    cols_features=cm["ns_reign_drought_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_reign_coups = api.Model(
    name="cm_ns_reign_coups",
    col_outcome=cm["ns_reign_coups"]["col_outcome"],
    cols_features=cm["ns_reign_coups"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_reign_coups_conf = api.Model(
    name="cm_ns_reign_coups_conf",
    col_outcome=cm["ns_reign_coups_conf"]["col_outcome"],
    cols_features=cm["ns_reign_coups_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_vdem = api.Model(
    name="cm_ns_vdem",
    col_outcome=cm["ns_vdem"]["col_outcome"],
    cols_features=cm["ns_vdem"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_vdem_conf = api.Model(
    name="cm_ns_vdem_conf",
    col_outcome=cm["ns_vdem_conf"]["col_outcome"],
    cols_features=cm["ns_vdem_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_vdem_high = api.Model(
    name="cm_ns_vdem_high",
    col_outcome=cm["ns_vdem_high"]["col_outcome"],
    cols_features=cm["ns_vdem_high"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_all_dummy = api.Model(
    name="cm_os_all_dummy",
    col_outcome=cm["os_all_dummy"]["col_outcome"],
    cols_features=cm["os_all_dummy"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_all_25 = api.Model(
    name="cm_os_all_25",
    col_outcome=cm["os_all_25"]["col_outcome"],
    cols_features=cm["os_all_25"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_acled_violence = api.Model(
    name="cm_os_acled_violence",
    col_outcome=cm["os_acled_violence"]["col_outcome"],
    cols_features=cm["os_acled_violence"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_acled_protest = api.Model(
    name="cm_os_acled_protest",
    col_outcome=cm["os_acled_protest"]["col_outcome"],
    cols_features=cm["os_acled_protest"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_cfshort = api.Model(
    name="cm_os_cfshort",
    col_outcome=cm["os_cfshort"]["col_outcome"],
    cols_features=cm["os_cfshort"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_cflong = api.Model(
    name="cm_os_cflong",
    col_outcome=cm["os_cflong"]["col_outcome"],
    cols_features=cm["os_cflong"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_demog = api.Model(
    name="cm_os_demog",
    col_outcome=cm["os_demog"]["col_outcome"],
    cols_features=cm["os_demog"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_demog_conf = api.Model(
    name="cm_os_demog_conf",
    col_outcome=cm["os_demog_conf"]["col_outcome"],
    cols_features=cm["os_demog_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_econ = api.Model(
    name="cm_os_econ",
    col_outcome=cm["os_econ"]["col_outcome"],
    cols_features=cm["os_econ"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_econ_conf = api.Model(
    name="cm_os_econ_conf",
    col_outcome=cm["os_econ_conf"]["col_outcome"],
    cols_features=cm["os_econ_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_inst = api.Model(
    name="cm_os_inst",
    col_outcome=cm["os_inst"]["col_outcome"],
    cols_features=cm["os_inst"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_inst_conf = api.Model(
    name="cm_os_inst_conf",
    col_outcome=cm["os_inst_conf"]["col_outcome"],
    cols_features=cm["os_inst_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_icgcw = api.Model(
    name="cm_os_icgcw",
    col_outcome=cm["os_icgcw"]["col_outcome"],
    cols_features=cm["os_icgcw"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_neibhist = api.Model(
    name="cm_os_neibhist",
    col_outcome=cm["os_neibhist"]["col_outcome"],
    cols_features=cm["os_neibhist"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_reign = api.Model(
    name="cm_os_reign",
    col_outcome=cm["os_reign"]["col_outcome"],
    cols_features=cm["os_reign"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_reign_conf = api.Model(
    name="cm_os_reign_conf",
    col_outcome=cm["os_reign_conf"]["col_outcome"],
    cols_features=cm["os_reign_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_reign_drought = api.Model(
    name="cm_os_reign_drought",
    col_outcome=cm["os_reign_drought"]["col_outcome"],
    cols_features=cm["os_reign_drought"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_reign_drought_conf = api.Model(
    name="cm_os_reign_drought_conf",
    col_outcome=cm["os_reign_drought_conf"]["col_outcome"],
    cols_features=cm["os_reign_drought_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_reign_coups = api.Model(
    name="cm_os_reign_coups",
    col_outcome=cm["os_reign_coups"]["col_outcome"],
    cols_features=cm["os_reign_coups"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_reign_coups_conf = api.Model(
    name="cm_os_reign_coups_conf",
    col_outcome=cm["os_reign_coups_conf"]["col_outcome"],
    cols_features=cm["os_reign_coups_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_vdem = api.Model(
    name="cm_os_vdem",
    col_outcome=cm["os_vdem"]["col_outcome"],
    cols_features=cm["os_vdem"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_vdem_conf = api.Model(
    name="cm_os_vdem_conf",
    col_outcome=cm["os_vdem_conf"]["col_outcome"],
    cols_features=cm["os_vdem_conf"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_vdem_high = api.Model(
    name="cm_os_vdem_high",
    col_outcome=cm["os_vdem_high"]["col_outcome"],
    cols_features=cm["os_vdem_high"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sbonset24_25_all = api.Model(
    name="cm_sbonset24_25_all",
    col_outcome=cm["sbonset24_25_all"]["col_outcome"],
    cols_features=cm["sbonset24_25_all"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    onset_outcome=True,
    onset_window=24,
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa", "onset"],
)
cm_nsonset24_25_all = api.Model(
    name="cm_nsonset24_25_all",
    col_outcome=cm["nsonset24_25_all"]["col_outcome"],
    cols_features=cm["nsonset24_25_all"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    onset_outcome=True,
    onset_window=24,
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa", "onset"],
)
cm_osonset24_25_all = api.Model(
    name="cm_osonset24_25_all",
    col_outcome=cm["osonset24_25_all"]["col_outcome"],
    cols_features=cm["osonset24_25_all"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    onset_outcome=True,
    onset_window=24,
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa", "onset"],
)
cm_sb100_all = api.Model(
    name="cm_sb100_all",
    col_outcome=cm["sb100_all"]["col_outcome"],
    cols_features=cm["sb100_all"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns100_all = api.Model(
    name="cm_ns100_all",
    col_outcome=cm["ns100_all"]["col_outcome"],
    cols_features=cm["ns100_all"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os100_all = api.Model(
    name="cm_os100_all",
    col_outcome=cm["os100_all"]["col_outcome"],
    cols_features=cm["os100_all"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_sb_cdummies = api.Model(
    name="cm_sb_cdummies",
    col_outcome=cm["sb_cdummies"]["col_outcome"],
    cols_features=cm["sb_cdummies"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_ns_cdummies = api.Model(
    name="cm_ns_cdummies",
    col_outcome=cm["ns_cdummies"]["col_outcome"],
    cols_features=cm["ns_cdummies"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)
cm_os_cdummies = api.Model(
    name="cm_os_cdummies",
    col_outcome=cm["os_cdummies"]["col_outcome"],
    cols_features=cm["os_cdummies"]["cols_features"],
    steps=steps,
    outcome_type="prob",
    estimator=rf,
    periods=periods,
    downsampling=fullsample,
    tags=["train_africa"],
)

all_cm_models: List[api.Model] = [
    cm_sb_vdem_global,
    cm_sb_wdi_global,
    cm_sb_reign_global,
    cm_sb_all_global,
    cm_ns_vdem_global,
    cm_ns_wdi_global,
    cm_ns_reign_global,
    cm_ns_all_global,
    cm_os_vdem_global,
    cm_os_wdi_global,
    cm_os_reign_global,
    cm_os_all_global,
    cm_sb_all_dummy,
    cm_sb_all_25,
    cm_sb_acled_violence,
    cm_sb_acled_protest,
    cm_sb_cfshort,
    cm_sb_cflong,
    cm_sb_demog,
    cm_sb_demog_conf,
    cm_sb_econ,
    cm_sb_econ_conf,
    cm_sb_inst,
    cm_sb_inst_conf,
    cm_sb_icgcw,
    cm_sb_icgcw_conf,
    cm_sb_neibhist,
    cm_sb_reign,
    cm_sb_reign_conf,
    cm_sb_reign_drought,
    cm_sb_reign_drought_conf,
    cm_sb_reign_coups,
    cm_sb_reign_coups_conf,
    cm_sb_vdem,
    cm_sb_vdem_conf,
    cm_sb_vdem_high,
    cm_ns_all_dummy,
    cm_ns_all_25,
    cm_ns_acled_violence,
    cm_ns_acled_protest,
    cm_ns_cfshort,
    cm_ns_cflong,
    cm_ns_demog,
    cm_ns_demog_conf,
    cm_ns_econ,
    cm_ns_econ_conf,
    cm_ns_inst,
    cm_ns_inst_conf,
    cm_ns_icgcw,
    cm_ns_neibhist,
    cm_ns_reign,
    cm_ns_reign_conf,
    cm_ns_reign_drought,
    cm_ns_reign_drought_conf,
    cm_ns_reign_coups,
    cm_ns_reign_coups_conf,
    cm_ns_vdem,
    cm_ns_vdem_conf,
    cm_ns_vdem_high,
    cm_os_all_dummy,
    cm_os_all_25,
    cm_os_acled_violence,
    cm_os_acled_protest,
    cm_os_cfshort,
    cm_os_cflong,
    cm_os_demog,
    cm_os_demog_conf,
    cm_os_econ,
    cm_os_econ_conf,
    cm_os_inst,
    cm_os_inst_conf,
    cm_os_icgcw,
    cm_os_neibhist,
    cm_os_reign,
    cm_os_reign_conf,
    cm_os_reign_drought,
    cm_os_reign_drought_conf,
    cm_os_reign_coups,
    cm_os_reign_coups_conf,
    cm_os_vdem,
    cm_os_vdem_conf,
    cm_os_vdem_high,
    cm_sbonset24_25_all,
    cm_nsonset24_25_all,
    cm_osonset24_25_all,
    cm_sb100_all,
    cm_ns100_all,
    cm_os100_all,
    cm_sb_cdummies,
    cm_ns_cdummies,
    cm_os_cdummies,
]

all_cm_models_by_name: Dict[str, api.Model] = dict()
for model in all_cm_models:
    all_cm_models_by_name[model.name] = model
